#!/bin/sh
if [ -z "$1" ]
  then
    echo "Specify root directory which contains train, test and validation folders"
    exit 1
fi

ROOT_DIR=$1

cd ../build
./calculate_optical_flow ${ROOT_DIR}/train/trial_000/rgb ${ROOT_DIR}/train/trial_000/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_000/rendered_body ${ROOT_DIR}/train/trial_000/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_001/rgb ${ROOT_DIR}/train/trial_001/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_001/rendered_body ${ROOT_DIR}/train/trial_001/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_002/rgb ${ROOT_DIR}/train/trial_002/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_002/rendered_body ${ROOT_DIR}/train/trial_002/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_003/rgb ${ROOT_DIR}/train/trial_003/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_003/rendered_body ${ROOT_DIR}/train/trial_003/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_004/rgb ${ROOT_DIR}/train/trial_004/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_004/rendered_body ${ROOT_DIR}/train/trial_004/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_005/rgb ${ROOT_DIR}/train/trial_005/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_005/rendered_body ${ROOT_DIR}/train/trial_005/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_006/rgb ${ROOT_DIR}/train/trial_006/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_006/rendered_body ${ROOT_DIR}/train/trial_006/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_007/rgb ${ROOT_DIR}/train/trial_007/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_007/rendered_body ${ROOT_DIR}/train/trial_007/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_008/rgb ${ROOT_DIR}/train/trial_008/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_008/rendered_body ${ROOT_DIR}/train/trial_008/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_009/rgb ${ROOT_DIR}/train/trial_009/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_009/rendered_body ${ROOT_DIR}/train/trial_009/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_010/rgb ${ROOT_DIR}/train/trial_010/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_010/rendered_body ${ROOT_DIR}/train/trial_010/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_011/rgb ${ROOT_DIR}/train/trial_011/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_011/rendered_body ${ROOT_DIR}/train/trial_011/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_012/rgb ${ROOT_DIR}/train/trial_012/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_012/rendered_body ${ROOT_DIR}/train/trial_012/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_013/rgb ${ROOT_DIR}/train/trial_013/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_013/rendered_body ${ROOT_DIR}/train/trial_013/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_014/rgb ${ROOT_DIR}/train/trial_014/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_014/rendered_body ${ROOT_DIR}/train/trial_014/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_015/rgb ${ROOT_DIR}/train/trial_015/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_015/rendered_body ${ROOT_DIR}/train/trial_015/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_016/rgb ${ROOT_DIR}/train/trial_016/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_016/rendered_body ${ROOT_DIR}/train/trial_016/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_017/rgb ${ROOT_DIR}/train/trial_017/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_017/rendered_body ${ROOT_DIR}/train/trial_017/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_018/rgb ${ROOT_DIR}/train/trial_018/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_018/rendered_body ${ROOT_DIR}/train/trial_018/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_019/rgb ${ROOT_DIR}/train/trial_019/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_019/rendered_body ${ROOT_DIR}/train/trial_019/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_020/rgb ${ROOT_DIR}/train/trial_020/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_020/rendered_body ${ROOT_DIR}/train/trial_020/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_021/rgb ${ROOT_DIR}/train/trial_021/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_021/rendered_body ${ROOT_DIR}/train/trial_021/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_022/rgb ${ROOT_DIR}/train/trial_022/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_022/rendered_body ${ROOT_DIR}/train/trial_022/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_023/rgb ${ROOT_DIR}/train/trial_023/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_023/rendered_body ${ROOT_DIR}/train/trial_023/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_024/rgb ${ROOT_DIR}/train/trial_024/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_024/rendered_body ${ROOT_DIR}/train/trial_024/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_025/rgb ${ROOT_DIR}/train/trial_025/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_025/rendered_body ${ROOT_DIR}/train/trial_025/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_026/rgb ${ROOT_DIR}/train/trial_026/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_026/rendered_body ${ROOT_DIR}/train/trial_026/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_027/rgb ${ROOT_DIR}/train/trial_027/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_027/rendered_body ${ROOT_DIR}/train/trial_027/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_028/rgb ${ROOT_DIR}/train/trial_028/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_028/rendered_body ${ROOT_DIR}/train/trial_028/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_029/rgb ${ROOT_DIR}/train/trial_029/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_029/rendered_body ${ROOT_DIR}/train/trial_029/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_030/rgb ${ROOT_DIR}/train/trial_030/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_030/rendered_body ${ROOT_DIR}/train/trial_030/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_031/rgb ${ROOT_DIR}/train/trial_031/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_031/rendered_body ${ROOT_DIR}/train/trial_031/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_032/rgb ${ROOT_DIR}/train/trial_032/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_032/rendered_body ${ROOT_DIR}/train/trial_032/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_033/rgb ${ROOT_DIR}/train/trial_033/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_033/rendered_body ${ROOT_DIR}/train/trial_033/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_034/rgb ${ROOT_DIR}/train/trial_034/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_034/rendered_body ${ROOT_DIR}/train/trial_034/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_035/rgb ${ROOT_DIR}/train/trial_035/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_035/rendered_body ${ROOT_DIR}/train/trial_035/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_036/rgb ${ROOT_DIR}/train/trial_036/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_036/rendered_body ${ROOT_DIR}/train/trial_036/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_037/rgb ${ROOT_DIR}/train/trial_037/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_037/rendered_body ${ROOT_DIR}/train/trial_037/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_038/rgb ${ROOT_DIR}/train/trial_038/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_038/rendered_body ${ROOT_DIR}/train/trial_038/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_039/rgb ${ROOT_DIR}/train/trial_039/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_039/rendered_body ${ROOT_DIR}/train/trial_039/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_040/rgb ${ROOT_DIR}/train/trial_040/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_040/rendered_body ${ROOT_DIR}/train/trial_040/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_041/rgb ${ROOT_DIR}/train/trial_041/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_041/rendered_body ${ROOT_DIR}/train/trial_041/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_042/rgb ${ROOT_DIR}/train/trial_042/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_042/rendered_body ${ROOT_DIR}/train/trial_042/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_043/rgb ${ROOT_DIR}/train/trial_043/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_043/rendered_body ${ROOT_DIR}/train/trial_043/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_044/rgb ${ROOT_DIR}/train/trial_044/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_044/rendered_body ${ROOT_DIR}/train/trial_044/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_045/rgb ${ROOT_DIR}/train/trial_045/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_045/rendered_body ${ROOT_DIR}/train/trial_045/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_046/rgb ${ROOT_DIR}/train/trial_046/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_046/rendered_body ${ROOT_DIR}/train/trial_046/body_flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_047/rgb ${ROOT_DIR}/train/trial_047/flow
./calculate_optical_flow ${ROOT_DIR}/train/trial_047/rendered_body ${ROOT_DIR}/train/trial_047/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_115/rgb ${ROOT_DIR}/validation/trial_115/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_115/rendered_body ${ROOT_DIR}/validation/trial_115/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_116/rgb ${ROOT_DIR}/validation/trial_116/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_116/rendered_body ${ROOT_DIR}/validation/trial_116/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_117/rgb ${ROOT_DIR}/validation/trial_117/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_117/rendered_body ${ROOT_DIR}/validation/trial_117/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_118/rgb ${ROOT_DIR}/validation/trial_118/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_118/rendered_body ${ROOT_DIR}/validation/trial_118/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_119/rgb ${ROOT_DIR}/validation/trial_119/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_119/rendered_body ${ROOT_DIR}/validation/trial_119/body_flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_120/rgb ${ROOT_DIR}/validation/trial_120/flow
./calculate_optical_flow ${ROOT_DIR}/validation/trial_120/rendered_body ${ROOT_DIR}/validation/trial_120/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_048/rgb ${ROOT_DIR}/test/trial_048/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_048/rendered_body ${ROOT_DIR}/test/trial_048/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_049/rgb ${ROOT_DIR}/test/trial_049/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_049/rendered_body ${ROOT_DIR}/test/trial_049/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_050/rgb ${ROOT_DIR}/test/trial_050/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_050/rendered_body ${ROOT_DIR}/test/trial_050/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_051/rgb ${ROOT_DIR}/test/trial_051/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_051/rendered_body ${ROOT_DIR}/test/trial_051/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_052/rgb ${ROOT_DIR}/test/trial_052/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_052/rendered_body ${ROOT_DIR}/test/trial_052/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_053/rgb ${ROOT_DIR}/test/trial_053/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_053/rendered_body ${ROOT_DIR}/test/trial_053/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_054/rgb ${ROOT_DIR}/test/trial_054/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_054/rendered_body ${ROOT_DIR}/test/trial_054/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_055/rgb ${ROOT_DIR}/test/trial_055/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_055/rendered_body ${ROOT_DIR}/test/trial_055/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_056/rgb ${ROOT_DIR}/test/trial_056/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_056/rendered_body ${ROOT_DIR}/test/trial_056/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_057/rgb ${ROOT_DIR}/test/trial_057/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_057/rendered_body ${ROOT_DIR}/test/trial_057/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_058/rgb ${ROOT_DIR}/test/trial_058/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_058/rendered_body ${ROOT_DIR}/test/trial_058/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_059/rgb ${ROOT_DIR}/test/trial_059/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_059/rendered_body ${ROOT_DIR}/test/trial_059/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_060/rgb ${ROOT_DIR}/test/trial_060/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_060/rendered_body ${ROOT_DIR}/test/trial_060/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_061/rgb ${ROOT_DIR}/test/trial_061/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_061/rendered_body ${ROOT_DIR}/test/trial_061/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_062/rgb ${ROOT_DIR}/test/trial_062/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_062/rendered_body ${ROOT_DIR}/test/trial_062/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_063/rgb ${ROOT_DIR}/test/trial_063/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_063/rendered_body ${ROOT_DIR}/test/trial_063/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_064/rgb ${ROOT_DIR}/test/trial_064/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_064/rendered_body ${ROOT_DIR}/test/trial_064/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_065/rgb ${ROOT_DIR}/test/trial_065/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_065/rendered_body ${ROOT_DIR}/test/trial_065/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_066/rgb ${ROOT_DIR}/test/trial_066/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_066/rendered_body ${ROOT_DIR}/test/trial_066/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_067/rgb ${ROOT_DIR}/test/trial_067/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_067/rendered_body ${ROOT_DIR}/test/trial_067/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_068/rgb ${ROOT_DIR}/test/trial_068/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_068/rendered_body ${ROOT_DIR}/test/trial_068/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_069/rgb ${ROOT_DIR}/test/trial_069/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_069/rendered_body ${ROOT_DIR}/test/trial_069/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_070/rgb ${ROOT_DIR}/test/trial_070/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_070/rendered_body ${ROOT_DIR}/test/trial_070/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_071/rgb ${ROOT_DIR}/test/trial_071/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_071/rendered_body ${ROOT_DIR}/test/trial_071/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_072/rgb ${ROOT_DIR}/test/trial_072/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_072/rendered_body ${ROOT_DIR}/test/trial_072/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_073/rgb ${ROOT_DIR}/test/trial_073/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_073/rendered_body ${ROOT_DIR}/test/trial_073/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_074/rgb ${ROOT_DIR}/test/trial_074/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_074/rendered_body ${ROOT_DIR}/test/trial_074/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_075/rgb ${ROOT_DIR}/test/trial_075/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_075/rendered_body ${ROOT_DIR}/test/trial_075/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_076/rgb ${ROOT_DIR}/test/trial_076/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_076/rendered_body ${ROOT_DIR}/test/trial_076/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_077/rgb ${ROOT_DIR}/test/trial_077/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_077/rendered_body ${ROOT_DIR}/test/trial_077/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_078/rgb ${ROOT_DIR}/test/trial_078/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_078/rendered_body ${ROOT_DIR}/test/trial_078/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_079/rgb ${ROOT_DIR}/test/trial_079/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_079/rendered_body ${ROOT_DIR}/test/trial_079/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_080/rgb ${ROOT_DIR}/test/trial_080/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_080/rendered_body ${ROOT_DIR}/test/trial_080/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_081/rgb ${ROOT_DIR}/test/trial_081/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_081/rendered_body ${ROOT_DIR}/test/trial_081/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_082/rgb ${ROOT_DIR}/test/trial_082/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_082/rendered_body ${ROOT_DIR}/test/trial_082/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_083/rgb ${ROOT_DIR}/test/trial_083/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_083/rendered_body ${ROOT_DIR}/test/trial_083/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_084/rgb ${ROOT_DIR}/test/trial_084/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_084/rendered_body ${ROOT_DIR}/test/trial_084/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_085/rgb ${ROOT_DIR}/test/trial_085/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_085/rendered_body ${ROOT_DIR}/test/trial_085/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_086/rgb ${ROOT_DIR}/test/trial_086/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_086/rendered_body ${ROOT_DIR}/test/trial_086/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_087/rgb ${ROOT_DIR}/test/trial_087/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_087/rendered_body ${ROOT_DIR}/test/trial_087/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_088/rgb ${ROOT_DIR}/test/trial_088/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_088/rendered_body ${ROOT_DIR}/test/trial_088/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_089/rgb ${ROOT_DIR}/test/trial_089/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_089/rendered_body ${ROOT_DIR}/test/trial_089/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_090/rgb ${ROOT_DIR}/test/trial_090/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_090/rendered_body ${ROOT_DIR}/test/trial_090/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_091/rgb ${ROOT_DIR}/test/trial_091/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_091/rendered_body ${ROOT_DIR}/test/trial_091/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_092/rgb ${ROOT_DIR}/test/trial_092/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_092/rendered_body ${ROOT_DIR}/test/trial_092/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_093/rgb ${ROOT_DIR}/test/trial_093/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_093/rendered_body ${ROOT_DIR}/test/trial_093/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_094/rgb ${ROOT_DIR}/test/trial_094/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_094/rendered_body ${ROOT_DIR}/test/trial_094/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_095/rgb ${ROOT_DIR}/test/trial_095/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_095/rendered_body ${ROOT_DIR}/test/trial_095/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_096/rgb ${ROOT_DIR}/test/trial_096/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_096/rendered_body ${ROOT_DIR}/test/trial_096/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_097/rgb ${ROOT_DIR}/test/trial_097/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_097/rendered_body ${ROOT_DIR}/test/trial_097/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_098/rgb ${ROOT_DIR}/test/trial_098/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_098/rendered_body ${ROOT_DIR}/test/trial_098/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_099/rgb ${ROOT_DIR}/test/trial_099/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_099/rendered_body ${ROOT_DIR}/test/trial_099/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_100/rgb ${ROOT_DIR}/test/trial_100/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_100/rendered_body ${ROOT_DIR}/test/trial_100/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_101/rgb ${ROOT_DIR}/test/trial_101/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_101/rendered_body ${ROOT_DIR}/test/trial_101/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_102/rgb ${ROOT_DIR}/test/trial_102/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_102/rendered_body ${ROOT_DIR}/test/trial_102/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_103/rgb ${ROOT_DIR}/test/trial_103/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_103/rendered_body ${ROOT_DIR}/test/trial_103/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_104/rgb ${ROOT_DIR}/test/trial_104/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_104/rendered_body ${ROOT_DIR}/test/trial_104/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_105/rgb ${ROOT_DIR}/test/trial_105/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_105/rendered_body ${ROOT_DIR}/test/trial_105/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_106/rgb ${ROOT_DIR}/test/trial_106/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_106/rendered_body ${ROOT_DIR}/test/trial_106/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_107/rgb ${ROOT_DIR}/test/trial_107/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_107/rendered_body ${ROOT_DIR}/test/trial_107/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_108/rgb ${ROOT_DIR}/test/trial_108/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_108/rendered_body ${ROOT_DIR}/test/trial_108/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_109/rgb ${ROOT_DIR}/test/trial_109/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_109/rendered_body ${ROOT_DIR}/test/trial_109/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_110/rgb ${ROOT_DIR}/test/trial_110/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_110/rendered_body ${ROOT_DIR}/test/trial_110/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_111/rgb ${ROOT_DIR}/test/trial_111/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_111/rendered_body ${ROOT_DIR}/test/trial_111/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_112/rgb ${ROOT_DIR}/test/trial_112/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_112/rendered_body ${ROOT_DIR}/test/trial_112/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_113/rgb ${ROOT_DIR}/test/trial_113/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_113/rendered_body ${ROOT_DIR}/test/trial_113/body_flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_114/rgb ${ROOT_DIR}/test/trial_114/flow
./calculate_optical_flow ${ROOT_DIR}/test/trial_114/rendered_body ${ROOT_DIR}/test/trial_114/body_flow
