theme: jekyll-theme-dinky
title: [motion anomaly detection]
zenodo:
    dataset_url: https://zenodo.org/record/4578539
publication:
    pdf_url: https://arxiv.org/pdf/2107.14206.pdf
github:
  is_project_page: False
